Added write-ups
SalonDesDevs/ctf-writeups pull request #7
Opened 2021-04-17 17:31 UTC by FrenchMasterSword

needs images files or existing links for a few WU of @clemg

2021-04-17 17:32 UTC, lightdiscord requested changes
Missing changes in SUMMARY.md

2021-04-17 17:41 UTC, ShiroUsagi-san approved these changes, later dismissed

2021-04-17 18:20 UTC, lightdiscord requested changes

2021-04-17 18:20 UTC, lightdiscord commented on src/SUMMARY.md
> +    - [WE-3](./Phack2021/Amuse_bouche/WE-1/README.md)
Wrong path

2021-04-17 18:20 UTC, lightdiscord commented on src/SUMMARY.md
> +    - [To_B,or_!_to_B](./Phack2021/System/To_B,or_!_to_B/README.md)
It seems special chars are not the best inside the file path, mdbook can't find the correct file

2021-04-17 18:20 UTC, lightdiscord commented on src/SUMMARY.md
> +    - [Harduino](./Phack2021/System/Harduino/README.md)
Wrong subfolder, `s/System/Web/`

2021-04-17 19:08 UTC, lightdiscord approved these changes

2021-04-18 12:59 UTC, ShiroUsagi-san approved these changes

2021-04-18 16:40 UTC, merged