cyber-apocalypse-2021: pwn writeups
SalonDesDevs/ctf-writeups pull request #9
Opened 2021-04-23 22:37 UTC by lightdiscord

2021-04-25 20:34 UTC, ShiroUsagi-san submitted a review, later dismissed

2021-04-26 09:56 UTC, clemg requested changes
Corrected only typos _not because I don't understand everything_

2021-04-26 09:56 UTC, clemg commented on src/cyber-apocalypse-2021/pwn/controller/attack.py
> +        # The payload will consists of the beginning garbage bytes then we will
I would rather say "consist" than "consists"

2021-04-26 09:56 UTC, clemg commented on src/cyber-apocalypse-2021/pwn/save-the-environment/README.md
> +at least 10 recycling point we can ask to leak an arbitrary address.
Points should be plural, since we have many ones

2021-04-26 09:56 UTC, clemg commented on src/cyber-apocalypse-2021/pwn/system-drop/README.md
> +And then returns 1.
Type: A should be lowercase :)

2021-04-26 09:56 UTC, clemg commented on src/cyber-apocalypse-2021/pwn/system-drop/README.md
> +Now that we have a shell! All we need is to cat the flag!
Strange formulation ? Either the first exclamation mark should be a comma, either the first "that" should be removed.

2021-04-26 11:32 UTC, clemg approved these changes

2021-04-26 16:48 UTC, DeltaEvo approved these changes

2021-04-26 17:42 UTC, merged